### ISSUE TITLE
better bibtex citation keys not retrieved from zotero 4

### ISSUE THREAD

**Issue by bonderado** [rafaqz/citation.vim#17]
Hello, I love this plugin, thanks for your effort.

After the fix to issue #16, I find that I do not get the right citation keys from my zotero 4 database.
I am still using version 4 because it is currently shipped with Debian Buster.

I can work around this, by pinning the plugin to the previous commit (715e64786a7), but I thought to file the bug so that other users can find it as a reference.

With my plugin manager (Shougo/dein.vim) the workaround is: 
 call dein#add('rafaqz/citation.vim', {'rev': '715e64786a7'})

If fixing the issue for good is too difficult, at least the workaround (and similar for other plugin managers)  should be added to the documentation.

PS: after the downgrade I had to modify the database through zotero to force updating the cache.

**Comment by rafaqz** [comment]
Hey thanks for letting me know, and glad you like it! Sorry Zotero 4 topped working. I stopped actively supporting it after I personally upgraded (and forgot to keep a database copy for testing!). It also has a different database schema and file system layout so it's a little difficult.

Pinning an older version is a good idea. But you could also download and run zotero 5.0 and install it manually in /opt/zotero which was what I did for early testing. It's actually much faster and more stable than 4.0 so there are a lot of advantages besides this plugin working! Betterbibtex has finally migrated as well so there's not much to lose except an hour working out how to install it :)

**Comment by rafaqz** [comment]
Also you can also manually delete your cache file. I should really version the cache so that happens automatically!

**Comment by rafaqz** [comment]
Thinking about this I've never treated this plugin as if that many people use it that I need to maintain testing for multiple versions, but apparently I was wrong about that! In future I will keep virtual machines for testing multiple versions of Zotero/Better bibtex etc.

I don't really have time for setting up for Zotero 4 again to test any fixes, but I would be happy if anyone put in a pull request to revert the breaking changes, while maintaining current functionality.
