### ISSUE TITLE
key_format check

### ISSUE THREAD

**Issue by DancingQuanta** [rafaqz/citation.vim#21]
https://github.com/rafaqz/citation.vim/blob/dbe8a021b95b1688047632b77cedf88665dcd755/python/citation_vim/zotero/parser.py#L79

Empty strings `""` are 'falsy` so the conditional
```
if self.context['key_format']:
```
works as well and more clear that the string is non-empty. So I suggest refactor the codebase to use this for checking empty strings.

**Comment by rafaqz** [comment]
This is the only real python project I've worked on so I imagine there are little things like that everywhere!

If you want to clean anything like that up, go for it.
