### ISSUE TITLE
unite buffer "default" candidates are empty

### ISSUE THREAD

**Issue by alexjwilliams** [rafaqz/citation.vim#26]
I installed Unite and citation.vim, including most of the shortcuts that you list in the readme. I am successfully able to insert a citation using `[unite]c`, however I am not able to open a file from a citation under the cursor using `[unite]co`. When I enter the key combination `[unite]co` I get a message at the bottom of the vim window that reads: `[unite.vim] unite buffer "default" candidates are empty`. I am running gvim version 8.0.1453 and Zotero version 5.0.85. It would be great if you could point me in the right direction to get this fixed. Let me know if you need any more info.

**Comment by rafaqz** [comment]
First try the `[unite]ci` command included in the readme to see if you can bring up information about the entry in vim. Seems like the entry isn't actually in the database for some reason.

**Comment by alexjwilliams** [comment]
That command also yields the message `[unite.vim] unite buffer "default" candidates are empty`.

**Comment by rafaqz** [comment]
If you send a link to the paper I'll try it out. Could be a problem with the text encoding or something, but I'm not sure. Are you using betterbibtex in zotero?

**Comment by alexjwilliams** [comment]
The error message displays for all citations that I try `[unite]co` on; it is not specific to one paper. I am using betterbibtex in Zotero.

**Comment by alexjwilliams** [comment]
I tried using the following minimal .vimrc file:

```set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'shougo/unite.vim'
Plug 'rafaqz/citation.vim'
let g:citation_vim_cache_path='~/.vim/citation-vim-cache'
let g:citation_vim_mode="zotero"
let g:citation_vim_zotero_path="~/Zotero"
let g:citation_vim_zotero_version=5
let g:citation_vim_et_al_limit=2
call plug#end()
let mapleader = ','

" Set a unite leader:
nmap <leader>u [unite]
nnoremap [unite] <nop>

" insert a citation
nnoremap <silent>[unite]c       :<C-u>Unite -buffer-name=citation-start-insert -default-action=append      citation/key<cr>

" immediately open a file from a citation under the cursor:
nnoremap <silent>[unite]co :<C-u>Unite -input=<C-R><C-W> -default-action=start -force-immediately citation/file<cr>

" open a url from a citation under the cursor:
nnoremap <silent><leader>cu :<C-u>Unite -input=<C-R><C-W> -default-action=start -force-immediately citation/url<cr>

" browse the file folder from a citation under the cursor:
nnoremap <silent>[unite]cf :<C-u>Unite -input=<C-R><C-W> -default-action=file -force-immediately citation/file<cr>

" to view all citation information from a citation under the cursor:
nnoremap <silent>[unite]ci :<C-u>Unite -input=<C-R><C-W> -default-action=preview -force-immediately citation/combined<cr>

" to preview, append, yank any other citation data you want from unite:
nnoremap <silent>[unite]cp :<C-u>Unite -default-action=yank citation/your_source_here<cr>

" search for the word under the cursor:
nnoremap <silent>[unite]cs :<C-u>Unite  -default-action=yank  citation/key:<C-R><C-W><cr>

" search for selected words in visual mode (notice that spaces have to be escaped) :
vnoremap <silent>[unite]cs :<C-u>exec "Unite  -default-action=start citation/key:" . escape(@*,' ') <cr>

" type search terms in the prompt:
nnoremap <silent>[unite]cx :<C-u>exec "Unite  -default-action=start citation/key:" . escape(input('Search Key : '),' ') <cr>

syntax enable 
```

With this file, I was successfully able to use `[unite]ci` to get the info of citations. However, there were still a few issues:

1. I was able to use `[unite]co` to open **pdf files** associated to Zotero entries. If the Zotero entry was for a web page, then using `[unite]co` simply opened up a Nautilus window (the file browser on Ubuntu) displaying my home directory, rather than opening the link in a web browser. 

2. Also, when I execute `[unite]co` with the cursor over the bracket character `]` of a citation, the incorrect pdf from Zotero would open. The same incorrect pdf would open when I tried this on several different citations. When I execute `[unite]ci` with the cursor over the bracket character `]` of a citation, the info of the incorrect pdf that I just referenced is displayed.

**Comment by rafaqz** [comment]
Ok that's good to hear.

1. If the entry is for just a web page, there is nothing in the file field. So it just opens an empty folder path because doing that is hard coded in Unite. I can't stop it if there is no actual file. 

If the entry has a url its in the url field - so you have to use the url source - because they can also have both at the same time. It could be possible to copy the url to the file field if there is no file, as a convenience. I'd accept a PR that did that.

2. The bracket character counts as a whole word in vim (press w on it to see) so you are effectively sending just the word "[" to search the zotero database when you do that. It just returns the closest random thing it can find. Basically the cursor must be inside the bracket.

**Comment by alexjwilliams** [comment]
Thanks for your response. I will try to work on a pull request in the next month or so, when I have time.
