### ISSUE TITLE
Question about generating bib files from Zotero in-line citations

### ISSUE THREAD

**Issue by johnabs** [rafaqz/citation.vim#27]
I just installed this plugin along with a few others and it is an absolute game changer! I'm ridiculously impressed at how easy it is to directly reach into Zotero and search for/pull out/read my citations. I do have one question though. Let's say I create Manuscript.tex, and start citing a bunch of stuff from Zotero. I want to compile the document, but can't as the .bib file is not present, but I definitely didn't use my whole library or collection. Would there be a way to collect those in-line citations and tell Zotero to create a new bib file in the current directory so things will compile?  If you have any ideas on what can point me in the right direction that I can mess around with, I would seriously appreciate it, and thank you for this awesome plugin!

**Comment by rafaqz** [comment]
Good to hear! Yeah I'm constantly surprised how much more powerful it is than the word/openoffice options.

For the bitex file, are you using BetterBibtex with Zotero? it takes carer of automatic bibtex exports. I just set it to export the whole thing to a file I link into my build scripts. 

BetterBibtex also integrates well with this plugin.
