### ISSUE TITLE
ddu.vim support

### ISSUE THREAD

**Issue by pou2** [rafaqz/citation.vim#29]
I know this is very much a long shot given that there was never time to get denite.vim support implemented, but could you make a quick assessment of how hard it would be to implement something like this for ddu.vim, the successor to denite.vim? (If it is going to take you a long time, then it's OK to decline and save your time of course). My coding background is pretty amateur, so it would probably be more than I could handle, but I might make the crazy decision to give it a shot. More likely, though, is that I will just use unite.vim and be very grateful for what I have.

**Comment by rafaqz** [comment]
I dont have time to do this and likely never will (or honestly the need for it, it works fine as is).

If you want it, learning vimscript/python and hacking away is the way to get it. I'll gladly review any PR here.

**Comment by pou2** [comment]
Sounds reasonable. I appreciate the willingness to review a PR. The likelihood I go after this is low, though, because like you said, it does work fine as it is.
